### ISSUE TITLE
`credentials_template.json` doesn't include shop?

### ISSUE THREAD

**Issue by reggi** [pixelcabin/ziplines_blank_template#1]
`credentials_template.json` doesn't include shop?

**Comment by michaelrshannon** [comment]
@reggi - the shop property is set in the `Gruntfile.js` - this is because this is a non-secret constant that can be committed to the repo and is not a per-developer property, unlike those found in `credentials.json`.

**Comment by reggi** [comment]
Gotcha! I'm digging through the commands, is there any way to set all the creds without setting up a new shop in a blank dir?

**Comment by michaelrshannon** [comment]
The setup Ziplines currently supports is geared around a new project, as there is very little further setup needed once an initial project is set up, except for copying `credentials_template.json` to `credentials.json`, and filling in the non-committed properties (API credentials and developer-specific theme_id). A future feature is to improve the support for jumping in to a pre-existing project, but has yet to be developed. Hope that helps!

**Comment by reggi** [comment]
:+1:
